#!/bin/sh -e

# Copyright: (C) 2008-2024 Kel Modderman <kelvmod@gmail.com>
# License:   GPLv2 or any later version

# By default we execute this as root user
ROOTEXEC=yes

# Locate directory we are called from
THIS_DIR=$(dirname $(readlink -f ${0}))

# Locate pyfll: prefer source tree layout, fall back to installed PATH
if [ -f "${THIS_DIR}/bin/pyfll" ]; then
	FLL="${THIS_DIR}/bin/pyfll"
elif command -v pyfll >/dev/null 2>&1; then
	FLL="$(command -v pyfll)"
else
	echo "Error locating pyfll, aborting." >&2
	exit 1
fi

# Get callers uid and gid for permission adjustment
USER_UID=$(getent passwd ${USER} | cut -d\: -f3)
USER_GID=$(getent passwd ${USER} | cut -d\: -f4)

for arg in ${@}; do
	case "${arg}" in
		-h*|--help|-n*|--non-root)
			ROOTEXEC=no
			break
			;;
	esac
done

if [ "${ROOTEXEC}" = yes ]; then
	if groups | grep -wq sudo; then
		exec sudo "${FLL}" --uid ${USER_UID} --gid ${USER_GID} ${@}
	else
		ROOT_CMD="${FLL} --uid ${USER_UID} --gid ${USER_GID} ${@}"
		exec su --command "${ROOT_CMD}" root
	fi
else
	exec "${FLL}" ${@}
fi
