#!/bin/sh -e

say() {
	echo "I: $@..."
}

do_postinst() {
	say "Creating /usr/share/wayland-sessions/kodi-flatpak.desktop"
	cat >/usr/share/wayland-sessions/kodi-flatpak.desktop <<EOF
[Desktop Entry]
Name=Kodi flatpak
Comment=Kodi flatpak
Exec=flatpak run tv.kodi.Kodi --standalone --windowing=gbm
Type=Application
EOF
}

case "${1}" in
	postinst)
		do_postinst
		;;
	*)
		echo "Usage: ${0} postinst"
		;;
esac

:
