#!/bin/sh -e

say() {
	echo "I: $@..."
}

do_postinst() {
	. /etc/default/distro
	say "Patching LXDE defaults"
	cp /usr/share/aptosid-settings-lxde/lxpanel/LXDE/panels/panel \
		/etc/xdg/lxpanel/LXDE/panels/panel
	cp /usr/share/aptosid-settings-lxde/lxsession/LXDE/desktop.conf \
		/etc/xdg/lxsession/LXDE/desktop.conf
	cp /usr/share/aptosid-settings-lxde/openbox/lxde-rc.xml \
		/etc/xdg/openbox/LXDE/rc.xml
	sed -i "s#^wallpaper=.*#wallpaper=${FLL_WALLPAPER}-wide.png#" \
		/etc/xdg/pcmanfm/LXDE/pcmanfm.conf
}

case "${1}" in
	postinst)
		do_postinst
		;;
	*)
		echo "Usage: ${0} postinst"
		;;
esac

:
