#!/bin/sh -e

say() {
	echo "I: $@..."
}

do_postinst() {
	say "Setting wlogout defaults"
	sed -i 's#loginctl lock-session#gtklock -i#' \
		/etc/wlogout/layout
	say "setting waybar defaults"
	cp /usr/share/aptosid-settings-hyprland/waybar/config.jsonc \
		/etc/xdg/waybar/config.jsonc
	cp /usr/share/aptosid-settings-hyprland/waybar/style.css \
		/etc/xdg/waybar/style.css
}

case "${1}" in
	postinst)
		do_postinst
		;;
	*)
		echo "Usage: ${0} postinst"
		;;
esac

:
