#!/bin/sh -e

#
# This script is executed in the chroot just before the final clean up.
#
# At the time of execution, no access to the wild is possible (eg, apt-get).
#
# /etc/default/distro will be sourced, and those variables are available
# for use.
#

. /etc/default/distro

# Disable bitmap fonts, they are fugly
if [ ! -L /etc/fonts/conf.d/70-no-bitmaps.conf ] && \
	[ -f /etc/fonts/conf.avail/70-no-bitmaps.conf ]; then
	echo 'Disabling bitmap fonts...'
	ln -s /etc/fonts/conf.avail/70-no-bitmaps.conf \
		/etc/fonts/conf.d/70-no-bitmaps.conf
fi


# Update menu system, fluxbox _needs_ this
if [ -x /usr/bin/update-menus ]; then
	echo 'Updating menus...'
	/usr/bin/update-menus
fi


# Prepare defaults for users of this system
echo 'Disabling system wide readable /home...'
sed -i 's/^DIR_MODE=.*/DIR_MODE=0751/' /etc/adduser.conf

echo 'Configuring adduser.conf for extra groups...'
EXTRA_GROUPS=
for g in ${FLL_LIVE_USER_GROUPS}; do
	if getent group ${g} >/dev/null; then
		EXTRA_GROUPS="${EXTRA_GROUPS} ${g}"
	fi
done

if [ "${EXTRA_GROUPS}" ]; then
	sed -i -e 's/^#\?\(EXTRA_GROUPS=\).*/\1"'"${EXTRA_GROUPS# }"'"/' \
	       -e 's/^#\?\(ADD_EXTRA_GROUPS=\).*/\11/' \
		/etc/adduser.conf
fi

# Secure the root account
echo 'Locking down root account...'
sed -i 's#^root:[^:]*:#root:\*:#' /etc/shadow
chmod 0751 /root

# Disable lastlog for autologin on console
if [ -w /etc/pam.d/login ]; then
	echo 'Disabling pam_lastlog...'
	sed -i '/^[^#].*pam_lastlog\.so/s/^/# /' /etc/pam.d/login
fi

# Fix Debian kppp noauth defaults
if [ -w /etc/ppp/peers/kppp-options ]; then
	echo 'Allowing KPPP noauth...'
	sed -i 's/^#noauth/noauth/' /etc/ppp/peers/kppp-options
fi

# Do not wait for maintainer to fix his package...
if [ -x /etc/init.d/irqbalance ]; then
	echo 'Removing irqbalance shutdown links...'
	rm -f /etc/rc[06].d/K??irqbalance
fi
