name: tests

on:
  push:
    branches: [master]
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    container: debian:sid
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            ca-certificates git python3 python3-configobj python3-debian python3-pytest
      - uses: actions/checkout@v4
      - run: python3 -m pytest -q
